### ISSUE TITLE
lalrpop v0.19.8 will be rejected by a future version of Rust

### ISSUE THREAD

**Issue by cottinisimone** [drjokepu/basic-cookies#4]
Hello and thank you for this lib. 

I receive this warning running clippy.

```
warning: the following packages contain code that will be rejected by a future version of Rust: lalrpop v0.19.8
```

Not sure if this might fix but can you please update `lalrpop-util` version to 0.20.0?

Thank you in advance

**Comment by drjokepu** [comment]
ok, this has been released
